# Imports
import = [
    "~/.config/alacritty/theme.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 20
padding.y = 20
dimensions.columns = 90
dimensions.lines = 25
opacity = 1.0
option_as_alt = "Both"

[font]
size = 13

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

